import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/keybindings.toml",
]

[font]
size = 14.5

[font.normal]
# family = "HackGen Console NF"
family = "FiraCode Nerd Font"

[window]
decorations = "none"
startup_mode = "Maximized"
padding.x = 8
padding.y = 8
