export HISTSIZE=10000
export SAVEHIST=100000
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY
setopt HIST_NO_FUNCTIONS

HISTORY_IGNORE_=(
    "rm *"
    "trash *"
)

export HISTORY_IGNORE=$(IFS="|";echo "${HISTORY_IGNORE_[*]}")

unset HISTORY_IGNORE_
