#!/bin/zsh

if battery_info=$(/usr/bin/pmset -g ps | awk '{ if (NR == 2) print $3 " " $4 }' | sed -e "s/;//g" -e "s/%//") ; then
  battery_quantity=$(echo $battery_info | awk '{print $1}')
  if [[ ! $battery_info =~ "discharging" ]]; then
    battery="#[fg=colour2,bg=status_bg_black] $battery_quantity% #[default]"
  elif (( $battery_quantity > 90 )); then
    battery="#[fg=colour2,bg=status_bg_black] $battery_quantity% #[default]"
  elif (( $battery_quantity > 80 )); then
    battery="#[fg=colour2,bg=status_bg_black] $battery_quantity% #[default]"
  elif (( $battery_quantity > 70 )); then
    battery="#[fg=colour2,bg=status_bg_black]   $battery_quantity% #[default]"
  elif (( $battery_quantity > 60 )); then
    battery="#[fg=colour2,bg=status_bg_black] $battery_quantity% #[default]"
  elif (( $battery_quantity > 50 )); then
    battery="#[fg=colour2,bg=status_bg_black] $battery_quantity% #[default]"
  elif (( $battery_quantity > 40 )); then
    battery="#[fg=colour2,bg=status_bg_black] $battery_quantity% #[default]"
  elif (( $battery_quantity > 30 )); then
    battery="#[fg=colour11,bg=status_bg_black] $battery_quantity% #[default]"
  elif (( $battery_quantity > 20 )); then
    battery="#[fg=colour11,bg=status_bg_black] $battery_quantity% #[default]"
  elif (( $battery_quantity > 10 )); then
    battery="#[fg=colour9,bg=status_bg_black] $battery_quantity% #[default]"
  elif (( $battery_quantity > 5 )); then
    battery="#[fg=colour9,bg=status_bg_black] $battery_quantity% #[default]"
  elif (( $battery_quantity > 0 )); then
    battery="#[fg=colour9,bg=status_bg_black] $battery_quantity% #[default]"
  else
    battery="#[fg=colour124,bg=status_bg_black] $battery_quantity% #[default]"
  fi
  echo $battery
fi
