# https://taskfile.dev

version: '3'

vars:
  BUILD_DIR: build


tasks:
  cmake:
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -GNinja -DCMAKE_INSTALL_PREFIX=$HOME/.local
    sources:
      - ./CMakeLists.txt
    generates:
      - ./{{.BUILD_DIR}}/CMakeCache.txt
    env:
      CXX: /opt/homebrew/opt/llvm/bin/clang++
  build:
    cmds:
      - task: cmake
      - cmake --build build --target install
    env:
      CXX: /opt/homebrew/opt/llvm/bin/clang++
