# https://taskfile.dev

version: '3'

vars:
  BUILD_DIR: build


tasks:
  cmake:
    cmds:
      - cmake -B {{.BUILD_DIR}} -S . -GNinja
    sources:
      - ./CMakeLists.txt
    generates:
      - ./{{.BUILD_DIR}}/CMakeCache.txt
  build:
    cmds:
      - task: cmake
      - cmake --build build --target install
